languageCode = "ja"
languageName = "Japanese"
displayName = "日本語"
isoCode = "ja"
weight = 1
rtl = false

title = "EveRun since 1989"
logo = "img/logo.jpg"
description = "東北大学のランニングサークル・イブランのホームページです"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "東北大学ランニングサークル・イブラン"
  image = "img/logo.jpg"
  headline = "現役メンバーを募集中！我こそはという人はご連絡ください！"
  bio = "東北大学の有志によるランニングサークルです。陸上部とは違い、そこまで本気にならずに、好きなペースで、好きな距離を走るサークルです。"
  links = [
    { twitter = "https://twitter.com/everun1989" },
    { facebook = "https://www.facebook.com/groups/everun/" },
    { instagram = "https://instagram.com/everun1982" },
    { email = "mailto:info@everun.club" },
  ]
